lesson_03
js-tasks-ru/jsbasic-20201008_9251580262 pull request #4
Opened 2020-10-15 20:12 UTC by Anton-CSS

2020-10-15 20:19 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-10-16 20:18 UTC, stas-dolgachov requested changes

2020-10-16 20:18 UTC, stas-dolgachov commented on 1-module/2-task/index.js
> +q
Удалите, пожалуйста, этот символ отсюда. Из-за него автоматическая проверка не может быть выполнена.

2020-10-16 20:18 UTC, stas-dolgachov commented on 2-module/1-task/index.js
> +  let sum = 0;
👍

2020-10-16 20:18 UTC, stas-dolgachov commented on 2-module/2-task/index.js
> +  let result = Object.values(obj);
👍

2020-10-16 20:18 UTC, stas-dolgachov commented on 2-module/3-task/index.js
> +  read(a, b){
👍

2020-10-17 18:22 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Определите, пуст ли объект
+ объект со свойством undefined должен считаться не пустым
+ {} должен вернуть true
+ если у объекта есть хоть одно свойство, то он не пустой
+ объект с удалённым свойством - пустой
```
```diff
Функция sumSalary(salaries)
+ должна складывать все зарплаты
+ должна возвращать 0 если нет свойств с зарплатами
+ должна игнорировать свойства других типов
```
```diff
Создайте калькулятор
+ должно умножать числа
+ должно складывать числа
```

Добавляю преподавателя (@stas-dolgachov) для код-ревью, посмотрим что он скажет :)

2020-10-19 10:24 UTC, stas-dolgachov approved these changes

2020-10-19 10:25 UTC, merged